name: Deploy Lambda Function

on:
  push:
    branches:
      - main
    paths:
      - 'a-01-ec2-instance-management/**'
      - '.github/workflows/deploy-lambda.yml'

  workflow_dispatch:

jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Package The Lambda Function
      run: |
        cd a-01-ec2-instance-management
        zip lambda.zip lambda_function.py

    - name: Deploy Lambda Function
      run: |
        aws lambda update-function-code \
          --function-name ec2-instance-manager \
          --zip-file fileb://a-01-ec2-instance-management/lambda.zip